### ISSUE TITLE
pep8 check broken in Travis

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintainer-quality-tools#163]
It seems that current version of pep8 is broken, leading to a false Travis error:

https://travis-ci.org/OCA/web/jobs/49936956

**Comment by pedrobaeza** [comment]
The issue is treated here: https://github.com/jcrocholl/pep8/issues/377

**Comment by pedrobaeza** [comment]
It has been solved quickly by @IanLee1521, so I close the issue. If you have one Travis test affected, please restart it to get the version with the fix applied.

**Comment by max3903** [comment]
I did restart this one:
https://travis-ci.org/OCA/hr/builds/49863350

Still the same error.

**Comment by moylop260** [comment]
@max3903 
You don't have same error
You have a real flake8 error:
```bash
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg
status1=$?
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
./hr_employee_seniority/hr.py:60:20: E251 unexpected spaces around keyword / parameter equals
./hr_employee_seniority/hr.py:60:46: E251 unexpected spaces around keyword / parameter equals
status2=$?
```

![travis ci free hosted continuous integration platform for the open source community](https://cloud.githubusercontent.com/assets/6644187/6099995/35498724-afcc-11e4-9f08-68f71da1b5f3.png)

**Comment by max3903** [comment]
I have this error:
`UnboundLocalError: local variable 'local_dir' referenced before assignment`
here:
https://travis-ci.org/OCA/hr/jobs/49863352

**Comment by pedrobaeza** [comment]
Sorry, @max3903, but I'm not seeing that problem in the log you have referenced, As @moylop260 says, you have real flake8 issues.
